### ISSUE TITLE
Isn't Lightweight Render Pipeline Deprecated?

### ISSUE THREAD

**Issue by tylo** [adrian-miasik/unity-shaders#6]
Unity deprecated the LWRP for the URP, right? I know LWRP still exists in the package manager, but I am not sure why.

Anyway, as someone who has URP installed, I had to change the paths in shaders that reference the LWRP.

**Comment by adrian-miasik** [comment]
I've targeted the LTS branch of Unity for initial release. There's still a ton of dev's working there and I wanted people to have the option to rollback/stay on an LTS version of Unity. (especially given the current state of Unity)

That being said, I haven't forgotten about URP. I'll be porting this to a later version of Unity when I have some free time. That means upgrading from LWRP to URP and a ton of other fun things 😅

So to answer your question: 
Yah. LWRP is deprecated.

But URP support will be something I'll be looking into.

**Comment by adrian-miasik** [comment]
Hey, I've created a release that supports URP and fixes some of the shaders. I'm going to write up a proper release post sometime tomorrow. 

If you want to get your hands on it before then: https://github.com/adrian-miasik/unity-shaders/releases/tag/v1.1.0

**Comment by adrian-miasik** [comment]
Thanks @tylo for submitting a ticket for this. 👍 
Release is out: https://github.com/adrian-miasik/unity-shaders/releases/tag/v1.1.0

Marking as fixed; closing issue.
